### ISSUE TITLE
Coheed and Cambria: Some albums are semi-duplicated.

### ISSUE THREAD

**Issue by pnomolos** [Shpigford/droptune#25]
https://droptune.co/artists/5818-coheed-and-cambria

Specifically:
- https://droptune.co/albums/112696-coheed-and-cambria-the-color-before-the-sun
- https://droptune.co/albums/112697-coheed-and-cambria-the-color-before-the-sun

- https://droptune.co/albums/112717-coheed-and-cambria-the-afterman-ascension-deluxe
- https://droptune.co/albums/112714-coheed-and-cambria-the-afterman-ascension-deluxe-edition

One listing includes Apple Music, the other doesn't.

**Comment by Shpigford** [comment]
@pnomolos Ah yes. This was an issue with viewing capitalization. Rolled a fix out, but it wasn't retroactive.
