### ISSUE TITLE
Mark albums as 'pre-release' if they are.

### ISSUE THREAD

**Issue by eelcojellema** [Shpigford/droptune#29]
Not sure if this is a Apple Music only thing or if Spotify does this too. Also happy to have a look at this and PR.

<img width="416" alt="screen shot 2018-08-20 at 23 26 29" src="https://user-images.githubusercontent.com/988051/44367595-8bc69400-a4d0-11e8-9e6d-48288c060186.png">

**Comment by Shpigford** [comment]
So, in theory these should only show up in the Upcoming section. Or are you suggesting add something to the album page itself?

**Comment by eelcojellema** [comment]
Weird. That looks like it is just that in practice. Could it be that albums on the profile pages are not filtered like that? Otherwise this issue can be removed.
