### ISSUE TITLE
Label "Singles" vs "Albums"

### ISSUE THREAD

**Issue by mtclmn** [Shpigford/droptune#31]
Cool project, @Shpigford!
One frustration I had with Spotify is their lack of labeling "singles" as such in New Releases.
Apple Music does a much better job of this, but it would be great to have consistent labels as to whether a new release is a single.

**Comment by ezekg** [comment]
Also, having the ability to filter by singles/albums would be rad.

**Comment by Shpigford** [comment]
Implemented!
