### ISSUE TITLE
Wrong username being displayed

### ISSUE THREAD

**Issue by fabiogiolito** [Shpigford/droptune#32]
Each time I refresh the page I see a new name on the navbar. Seems like logged username is being cached and I'm being served someone's cache.

![image](https://user-images.githubusercontent.com/81450/44554486-130e4480-a729-11e8-8a45-086d2a352761.png)

**Comment by Shpigford** [comment]
@fabiogiolito This should be fixed now. You may need to sign out and sign back in for it to pick up the proper username/avatar.
