### ISSUE TITLE
Can't sign up with Twitter or Spotify

### ISSUE THREAD

**Issue by ezekg** [Shpigford/droptune#34]
After signing up with Twitter (OAuth succeeded), I'm given sign up options again, which makes it seem like the registration failed (i.e. I'm not signed in and asked to sign up again):

![image](https://user-images.githubusercontent.com/6979737/44737354-5fee7400-aab7-11e8-9d46-aa7b852baa3d.png)

Then when I try to sign in with Twitter, it redirects me back to the same page after the successful OAuth. When I choose Spotify, I get a `406 Not Acceptable` HTTP response after a successful OAuth flow. I've tried revoking the Twitter OAuth access and going through the flow again to no avail.

**Comment by Shpigford** [comment]
@ezekg What's the URL for the page in that screenshot?

**Comment by ezekg** [comment]
https://droptune.co/users/sign_up

**Comment by Shpigford** [comment]
@ezekg Can you try again, maybe from a private browser session?

**Comment by Shpigford** [comment]
@ezekg 93.2% sure I found the issue and rolled out a fix. Let me know how it goes for you now.

**Comment by ezekg** [comment]
Works great now. 😄
