### ISSUE TITLE
Connections section in settings should reflect reality

### ISSUE THREAD

**Issue by tnorthcutt** [Shpigford/droptune#36]
_(This is not intended as a criticism; rather I'm hoping that pointing out potentially confusing UX issues is helpful 😄)_

Currently, the Connections section in settings does not update to reflect if a service is already connected. I've connected Spotify, but I'm still offered the option to... connect Spotify 😅 

![image](https://user-images.githubusercontent.com/796639/44749362-7e606980-aacf-11e8-9e71-8db7ca1ec9c1.png)

N.B. I also noticed that when initially connecting a service as prompted after signing in with Twitter, I was flashed a success message, but also still saw the prompt to connect. I didn't get a screenshot of that, though.

**Comment by Shpigford** [comment]
@tnorthcutt That whole "Connections" area should be a bit more intuitive now!

**Comment by tnorthcutt** [comment]
@Shpigford dude, that was scary fast! Very nice!

![george-costanza-bravo-clapping-seinfeld](https://user-images.githubusercontent.com/796639/44755275-b0c79200-aae2-11e8-82db-02cfe9f58e06.gif)
