### ISSUE TITLE
Create a custom Spotify playlist of recent releases

### ISSUE THREAD

**Issue by ezekg** [Shpigford/droptune#38]
I think this would be absolutely rad. Would be a nice to be able to just hit play and listen to the new music, instead of going to each album/single individually. Maybe offer the ability to e.g. filter out singles, include the full album in the playlist vs only X number of songs, and other customizations?

Spotify's API allows [playlist creation and management](https://developer.spotify.com/documentation/web-api/reference/playlists/). Not sure if Apple Music allows something similar, as I don't use it often, but that would be ideal.

Could probably use something like [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron) with [sidekiq-unique-jobs](https://github.com/mhenrixon/sidekiq-unique-jobs) to run a daily worker that keeps the playlist up to date (not 100% sure how things are currently set up but I'll dig in soon).

**Comment by Shpigford** [comment]
Absolutely fantastic idea!

**Comment by Shpigford** [comment]
Just making a note for future reference, Apple Music allows additive actions but not subtractive.

So, you can _create_ playlists or _add tracks to_ playlists but you can't delete playlists or delete tracks from playlists.

My initial thinking here was basically update a single "Droptune New Music" playlist every day with all music released in the past X days, so it'd be sort of a rolling dynamic list of new music.

Easy to do with Spotify, but not exactly possible with Apple Music.

One solution for Apple Music would be to just append new tracks and then let the user delete old ones themselves as they'd like. That, or just create a new playlist once a week (though that could quickly get out of hand).

**Comment by Shpigford** [comment]
Implemented this for Spotify! Apple Music will be coming soon.
