### ISSUE TITLE
Privacy settings

### ISSUE THREAD

**Issue by danielcompton** [Shpigford/droptune#61]
I was slightly surprised to see that all of my music preferences are publicly visible to everyone. It's not a huge deal for me, but it would probably be good to make that clearer to people, and also to give them the option (maybe the default?) for their profile and music preferences to be private. A music collection could reveal a lot of information about somebody, so people should be able to make a choice about it.

(I realise that this is all super early and I'm not upset/grumpy about this missing feature, just adding it as something to think about for the future).

**Comment by Shpigford** [comment]
You're saying you want a way to toggle the music that's in your collection being available for others to see?

**Comment by danielcompton** [comment]
Yeah maybe just toggle user visibility entirely would be easiest.

**Comment by Shpigford** [comment]
@danielcompton Rolled this out! Doesn't entirely had the actual profile itself, but hides all music listings from the public so you can't see who a given user listens to or follows.

Thanks for the suggestion!
