### ISSUE TITLE
Spotify embed is not embedded

### ISSUE THREAD

**Issue by tnorthcutt** [Shpigford/droptune#64]
This morning I noticed that album views do not seem to have a Spotify embed, whereas I recall them having that the list time I used Droptune.

I also noticed a js error in the devtools console; not sure if it's related:

![image](https://user-images.githubusercontent.com/796639/45043653-fe845300-b02a-11e8-913f-91f3019b1643.png)

Should there be a Spotify embed on this page? If so, is there anything I can do to help debug this further?

**Comment by Shpigford** [comment]
@tnorthcutt Give it a look now. There's a few things it tries to do to determine which player to show you and so I adjusted that.

**Comment by tnorthcutt** [comment]
@Shpigford Yep, working better now, thanks!

I'm curious: why default to Apple Music embeds (at least that's how I'm reading the source; maybe I'm wrong – I don't use Ruby much).

**Comment by Shpigford** [comment]
@tnorthcutt Well what I made it do now is say...

If user has connected Apple Music, show that player
Else if user has connected Spotify, show that player
Else show Apple Music

When it makes sense to, I try to default to the Apple Music player as it's just a much better player. Doesn't have as many in-browser issues, lets you add to your library right from the player, etc. Just a better experience.

That being said, if a user users Spotify, then it should now default to that player first over Apple Music, when available.

**Comment by tnorthcutt** [comment]
Roger that. Thanks for explaining the reasoning!
